name: deploy skippymart-products-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy_skippymart-products-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          # audience: ${{ secrets.AUDIENCE }}
          role-duration-seconds: 7200

      - name: Install zip tool
        uses: montudor/action-zip@v1

      - name: Create Zip file for Lambda function
        run: zip -r code.zip .

      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        with:
          args: >
            lambda update-function-code
            --function-name arn:aws:lambda:us-west-2:824333227939:function:skippymart-products-api
            --zip-file fileb://code.zip
