name: destroy skippymart-products-api

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy_skippymart-products-api:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_APP_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-duration-seconds: 7200

      # Checks if the function exists, deletes it if found, and gracefully skips if it's already gone
      - name: Destroy AWS Lambda
        run: |
          FUNCTION_NAME="skippymart-products-api"
          REGION="${{ secrets.AWS_REGION }}"

          echo "Checking if Lambda function exists..."
          if aws lambda get-function --function-name "$FUNCTION_NAME" --region "$REGION" >/dev/null 2>&1; then
            echo "Function exists. Destroying Lambda function..."
            aws lambda delete-function --function-name "$FUNCTION_NAME" --region "$REGION"
            echo "Lambda function '$FUNCTION_NAME' successfully destroyed."
          else
            echo "Lambda function '$FUNCTION_NAME' does not exist. Nothing to destroy."
          fi